sudo: false
language: ruby
node_js:
  - "4"
before_install:
  - npm install -g Financial-Times/origami-build-tools#node4
  - obt install
  - npm install -g node-sass # required for the tests  
script:
  - "test/travis.rb"
  - obt test
  - obt verify
cache:
  directories:
  - node_modules